# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # TruffleHog v3 - Security scanning for secrets
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.88.0  # Update to latest version
    hooks:
      - id: trufflehog
        name: TruffleHog Security Scan
        entry: trufflehog filesystem .
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]
        args: ['--only-verified', '--fail', '--no-update', '--exclude-paths', '.trufflehog-allowlist.txt']

  # uv pre-commit hooks
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.11  # Update to match your uv version
    hooks:
      - id: uv-lock
        name: Update uv.lock
        stages: [pre-commit]

  # Python code formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
      - id: ruff-format
        args: ['--line-length=320']

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: [types-psutil]
        args: ['--ignore-missing-imports']

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
        args: ['--fix=lf']

# Global configuration
default_language_version:
  python: python3.12

fail_fast: false
minimum_pre_commit_version: '3.5.0'
